### ISSUE TITLE
why does not the discriminator output a scalar

### ISSUE THREAD

**Issue by breadbread1984** [adepierre/Caffe_CycleGAN#1]
As far as I understand, the output of the discriminator outputs a scalar which represents whether the input comes from natural image set or generated image set. But I find that your discriminator outputs a 32x32 tensor. Could you explain the reason of that? Thx

**Comment by adepierre** [comment]
The disciminator 's architecture is basically the same they used in the paper. Instead of predicting one scalar value for the whole image, it predicts one scalar value for each pixel in the feature map (32x32 blob).

With this architecture, the network can have different gradient values for different parts of the image depending on how they look real or not.

**Comment by adepierre** [comment]
The disciminator's architecture is basically the same they used in the paper. Instead of predicting one scalar value for the whole image, it predicts one scalar value for each pixel in the feature map (32x32 blob).

With this architecture, the network can have different gradient values for different parts of the image depending on how they look real or not.
